### ISSUE TITLE
A machine-interpretable version of your article

### ISSUE THREAD

**Issue by jd-coderepos** [sebischair/KG-in-NLP-survey#1]
Dear authors,

I was wondering if the data annotated and published in your excellent survey article can also be released as a machine-interpretable, FAIR [1] version on the Open Research Knowledge Graph https://orkg.org/ ? Particularly relevant for creating the equivalent machine-actionable version of your article are the following ORKG features: https://orkg.org/comparisons , https://orkg.org/visualizations, and https://orkg.org/reviews . With the machine-actionable knowledge from your article, users can query the data for specialized views among other things.

I would be happy to offer further support to this end.

Best regards,
Jennifer (https://sites.google.com/view/jen-web)

[1] https://www.go-fair.org/fair-principles/

**Comment by philotron** [comment]
Dear Jennifer,

thanks for your message. I think this is a great idea. I will write you a mail for discussing the necessary actions.

Best regards,
Phillip
